applications:
  - name: applications
    namespace: argocd
    additionalLabels:
      owner: Mher
    project: default
    source:
        repoURL: https://github.com/ZapNURSE/sms-infrastructure.git
        targetRevision: develop
        path: modules/argocd/applications/develop
    sources:
      - repoURL: https://github.com/ZapNURSE/workforce-managent.git
        targetRevision: develop
        path: modules/argocd/applications/develop
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
          prune: true
          selfHeal: true