apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actrus-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZapNURSE/workforce-managent.git
    targetRevision: develop
    path: helm/actrus-api
    helm:
      releaseName: actrus-api
      valueFiles:
      - dev.yaml
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default