apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actrus-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: actrus-api=415172466759.dkr.ecr.us-west-2.amazonaws.com/actriv-dev-actrus-repository
    argocd-image-updater.argoproj.io/actrus-api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/actrus-api.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/actrus-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: develop
    argocd-image-updater.argoproj.io/actrus-api.allow-tags: regexp:^develop-*
spec:
  project: default
  source:
    repoURL: https://github.com/ZapNURSE/workforce-managent.git
    targetRevision: develop
    path: helm/actrus-api
    helm:
      releaseName: actrus-api
      valueFiles:
      - dev.yaml
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default