apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm/
    chart: argo-rollouts
    targetRevision: 2.31.0
    helm:
      values: |
        dashboard:
          enabled: true
          ingress:
            enabled: true
            pathType: Prefix
            paths:
                - /
            annotations:
              kubernetes.io/ingress.class: "nginx"
              ingressClassName: "nginx"
              nginx.ingress.kubernetes.io/certificate: "arn:aws:acm:us-west-2:415172466759:certificate/6f9e5a08-f007-4fa2-ab9d-810ddf282c11"
              external-dns.alpha.kubernetes.io/hostname: "argo-rollouts.dev.actriv.com"
              alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
              alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-2016-08"
            hosts: 
              - "argo-rollouts.dev.actriv.com"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc