apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudwatch-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 0.25.1
    chart: prometheus-cloudwatch-exporter
    helm:
      values: |
        aws:
          secret:
            name: aws-credentials
            includesSessionToken: false
        config: |-
            region: eu-west-2
            period_seconds: 240
            metrics:
                - aws_namespace: AWS/RDS
                  aws_metric_name: CPUUtilization
                  aws_dimensions: [DBInstanceIdentifier]
                  aws_statistics: [Average]

                - aws_namespace: AWS/RDS
                  aws_metric_name: DatabaseConnections
                  aws_dimensions: [DBInstanceIdentifier]
                  aws_statistics: [Average]

                - aws_namespace: AWS/RDS
                  aws_metric_name: FreeStorageSpace
                  aws_dimensions: [DBInstanceIdentifier]
                  aws_statistics: [Average]

                - aws_namespace: AWS/RDS
                  aws_metric_name: ReadIOPS
                  aws_dimensions: [DBInstanceIdentifier]
                  aws_statistics: [Average]

                - aws_namespace: AWS/RDS
                  aws_metric_name: WriteIOPS
                  aws_dimensions: [DBInstanceIdentifier]
                  aws_statistics: [Average]
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true