apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store-aws
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/ZapNURSE/sms-infrastructure.git
    targetRevision: develop
    path: helm-charts/kube-addons/cluster-secret-store
    helm:
      values: |
        awsRegion: us-east-1
        serviceAccountName: "external-secrets-sa"
        name: "aws-secretsmanager"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: kube-addons
    server: https://kubernetes.default.svc

