apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.8.1
    helm:
      values: |
        serviceAccount:
          create: true
          annotations: 
            eks\.amazonaws\.com/role-arn: 'arn:aws:iam::415172466759:role/actriv-dev-external-secrets-role'
          name: external-secrets-service-account
        podAnnotations:
          eks\.amazonaws\.com/role-arn: 'arn:aws:iam::415172466759:role/actriv-dev-external-secrets-role'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true