apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 8.5.5
    chart: kubernetes-external-secrets
    helm:
      values: |
        env:
          AWS_REGION: us-west-2
          POLLER_INTERVAL_MILLISECONDS : 10000
        serviceAccount:
          create: true
          annotations: 
            eks\.amazonaws\.com/role-arn: 'arn:aws:iam::415172466759:role/actriv-dev-external-secrets-role'
          name: external-secrets-service-account
        podAnnotations:
          eks\.amazonaws\.com/role-arn: 'arn:aws:iam::415172466759:role/actriv-dev-external-secrets-role'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true