apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: facility-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: facility-app=415172466759.dkr.ecr.us-west-2.amazonaws.com/actriv-dev-facility-app-repository
    argocd-image-updater.argoproj.io/facility-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/facility-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/facility-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: develop
spec:
  project: default
  source:
    repoURL: https://github.com/ZapNURSE/workforce-managent.git
    targetRevision: develop
    path: helm/facility-app
    helm:
      releaseName: facility-app
      valueFiles:
      - dev.yaml
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default