apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yace-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mogaal.github.io/helm-charts
    targetRevision: 0.5.0
    chart: prometheus-yace-exporter
    helm:
      values: |
        aws:
          secret:
            name: aws-credentials
            includesSessionToken: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
