apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yace-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://mogaal.github.io/helm-charts
    targetRevision: 0.5.0
    chart: prometheus-yace-exporter
    helm:
      values: |
        aws:
          secret:
            name: aws-credentials
            includesSessionToken: false
        config: |-
          discovery:
            jobs:
            - region: eu-west-2
              type: "AWS/RDS"
              metrics:
                - name: CPUUtilization
                  statistics:
                  - 'Maximum'
                  period: 600
                  length: 60
                - name: DatabaseConnections
                  statistics:
                  - 'Sum'
                  period: 600
                  length: 60
                - name: FreeableMemory
                  statistics:
                  - 'Average'
                  period: 600
                  length: 60
                - name: FreeStorageSpace
                  statistics:
                  - 'Average'
                  period: 600
                  length: 60
                - name: ReadThroughput
                  statistics:
                  - 'Average'
                  period: 600
                  length: 60                
                - name: WriteThroughput
                  statistics:
                  - 'Average'
                  period: 600
                  length: 60
                - name: ReadLatency
                  statistics:
                  - 'Maximum'
                  period: 600
                  length: 60                
                - name: WriteLatency
                  statistics:
                  - 'Maximum'
                  period: 600
                  length: 60
                - name: ReadIOPS
                  statistics:
                  - 'Average'
                  period: 600
                  length: 60                
                - name: WriteIOPS
                  statistics:
                  - 'Average'
                  period: 600
                  length: 60
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
