apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
  namespace: argocd
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.1
    helm:
      values: |
        config:
            registries:
              - name: ECR
                api_url: https://082380147777.dkr.ecr.us-west-2.amazonaws.com/
                prefix: 082380147777.dkr.ecr.us-west-2.amazonaws.com
                default: true
                ping: yes
                insecure: no
                credentials: ext:/scripts/ecr-login.sh  #script name should match here and in authScripts 
                credsexpire: 11h
        authScripts:
            enabled: true
            scripts: 
                ecr-login.sh: |   # notice script name matches above    
                  #!/bin/sh
                  aws ecr --region us-west-2 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d
        serviceAccount:
            annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::082380147777:role/image-updater-role
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc