apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: provider-app=082380147777.dkr.ecr.us-west-2.amazonaws.com/actriv-prod-provider-app-repository
    argocd-image-updater.argoproj.io/provider-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/provider-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/provider-app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: develop
spec:
  project: default
  source:
    repoURL: https://github.com/ZapNURSE/workforce-managent.git
    targetRevision: develop
    path: helm/provider-app
    helm:
      releaseName: provider-app
      valueFiles:
      - prod.yaml
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default