apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.8.1
    helm:
      values: |
        serviceAccount:
          create: true
          annotations: 
            eks.amazonaws.com/role-arn: 'arn:aws:iam::150042025240:role/external-secrets-role'
          name: 'external-secrets-role'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: kube-addons
    server: https://kubernetes.default.svc