apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  namespace: kube-system
  name: {{ .Values.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccountName }}
            namespace: {{ .Release.Namespace }}