name: Test
on:
  create:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ steps.prompt.outputs.branch_name }} on ${{ steps.prompt.outputs.environment }}
        run: |
          echo "Hello world"

